language: php

php:
  - 5.4

# dirty hack to attempt to ensure the existence of dependant components.
before_install: sleep 120
install: composer --dev install
script: ./vendor/bin/phpunit

notifications:
  irc:
    on_success: change
    on_failure: always
    channels:
      - "irc.freenode.net#proem"

branches:
  only:
    - master
    - develop
