language: php

php:
  - 5.4

before_script: composer --dev install
script: ./vendor/bin/phpunit

notifications:
  irc:
    on_success: change
    on_failure: always
    channels:
      - "irc.freenode.net#proem"

branches:
  only:
    - master
    - develop
